trigger:
  branches:
    include:
      - main
 
variables:
  projectPath: '$(Build.SourcesDirectory)/ScanlyApi/ScanlyApi.csproj'

  serviceConnection: 'scanly-connection'
  resourceGroup: 'RG-Daniel-Rank-64f115-DotNetCloudDeveloper-VT-Mars-Goteborg'

  acrName: 'scanlystageacr'
  imageName: 'scanlyapi'
  imageTag: '$(Build.BuildId)'

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self

#############
# Build .Net
#############

  - task: UseDotNet@2
    displayName: Use .NET SDK
    inputs:
      packageType: sdk
      version: '10.x'

  - script: dotnet restore "$(projectPath)"
    displayName: Restore

  - script: dotnet build "$(projectPath)" --configuration Release --no-restore
    displayName: Build

##########
# Deploy infrastructure
##########

  - task: AzureCLI@2
    displayName: Deploy infrastructure
    inputs:
      azureSubscription: '$(serviceConnection)'
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az deployment group create \
          --resource-group $(resourceGroup) \
          --template-file "$(Build.SourcesDirectory)/ScanlyApi/infra/main.bicep" \
          --parameters acrName=$(acrName) \
          --parameters Infra/stage.bicepparam \
          

#########
#Build and psuh Image to ACR
#########


  - task: AzureCLI@2
    displayName: Build and push image to ACR
    inputs:
      azureSubscription: '$(serviceConnection)'
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        # Login mot ACR
        az acr login --name $(acrName)

        # Build image
        docker build \
          -t $(acrName).azurecr.io/$(imageName):$(imageTag) \
          ScanlyApi/

        # Push image
        docker push \
          $(acrName).azurecr.io/$(imageName):$(imageTag)

#########
#Update Container App
#########

  - task: AzureCLI@2
    displayName: Update Container App
    inputs:
      azureSubscription: '$(serviceConnection)'
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az containerapp update \
          --name scanlyapi \
          --resource-group $(resourceGroup) \
          --image $(acrName).azurecr.io/$(imageName):$(imageTag)

