name: CI_CD

trigger:
  branches:
    include:
      - main

variables:
  projectPath: '$(Build.SourcesDirectory)/ScanlyApi/ScanlyApi.csproj'

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self

  - task: UseDotNet@2
    displayName: Use .NET SDK
    inputs:
      packageType: sdk
      version: '8.x'

  - script: dotnet restore "$(projectPath)"
    displayName: Restore

  - script: dotnet build "$(projectPath)" --configuration Release --no-restore
    displayName: Build

 