name: CI_CD_Github

on:
  push:
    branches:
      - main
    paths:
      - 'ScanlyApi/**'


jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore ScanlyApi/ScanlyApi.csproj

      - name: Build
        run: dotnet build ScanlyApi/ScanlyApi.csproj --configuration Release --no-restore

  build-image:
    runs-on: ubuntu-latest
    needs: build

    permission:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: | 
          docker build \
          -t scanlyapi:${{ github.sha }} \
          ScanlyApi/

      - name: Log in to Azure with OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

   